"""Structural contracts for pluggable animation backends.

Create clips on the library's GUI thread; warm_meta must be worker-safe.
warm_first_frame is optional and is detected by the warm-up scheduler.
"""
from __future__ import annotations
from pathlib import Path
from typing import Any, Protocol


class AnimationClip(Protocol):
    frameChanged: Any
    finished: Any
    errorOccurred: Any
    path: Path

    def start(self) -> None: ...
    def stop(self) -> None: ...
    def frameCount(self) -> int: ...
    def duration(self) -> float: ...
    def currentFrameNumber(self) -> int: ...
    def currentTimeSeconds(self) -> float: ...
    def currentPixmap(self) -> Any: ...
    def currentImage(self) -> Any: ...
    def jumpToFrame(self, frame_index: int) -> bool: ...
    def set_playback_speed(self, speed: float) -> None: ...
    def warm_meta(self) -> None: ...


class ClipFactory(Protocol):
    def __call__(self, path: Path, *, parent: Any = None) -> AnimationClip: ...
